// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD76c0aZrG6Z5g6mlwapPzW9QeMSa8LyXo',
    appId: '1:263336994953:web:3bc3b28415da1eefbb7e58',
    messagingSenderId: '263336994953',
    projectId: 'panda-live-app',
    authDomain: 'panda-live-app.firebaseapp.com',
    storageBucket: 'panda-live-app.firebasestorage.app',
    measurementId: 'G-CVNSJ3CV66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCndv6uzC2zR77MxRuKvPctp9g4bS8h5Os',
    appId: '1:263336994953:android:2bc9fe2e96c46cf8bb7e58',
    messagingSenderId: '263336994953',
    projectId: 'panda-live-app',
    storageBucket: 'panda-live-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN229bx5rx_xSeORrhT4yWs5APX6NkH-M',
    appId: '1:263336994953:ios:7874dcdbf251fa3dbb7e58',
    messagingSenderId: '263336994953',
    projectId: 'panda-live-app',
    storageBucket: 'panda-live-app.firebasestorage.app',
    androidClientId: '263336994953-2764nu4o47lfli377kkr7t9k9g0upfrm.apps.googleusercontent.com',
    iosClientId: '263336994953-tct2t27oepdi2t201fnblfsat5belgjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pandaAdminpanel',
  );
}
