import 'package:get/get.dart';

class AppLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en_US": {
      "home": "Home",
      "user": "ManageUser",
      "wallet": 'Wallet',
      "language": "Language",
      "no live": "No one Live NOw",
      "totaluser": "Total App Users",
      "follow": "Follow",
      "follower": "Follower",
      "manage": 'Manage',
      "blockuser": "Blocked Users",
      "unblock": "Unblock",
      "pandauser": "Beloved Panda Live User",
      "country": "Country",
      "weekcoins": "Week Earned Coins",
      "weekearn": "Week Earnings",
      "totalwid": "Total Withdrawl Ammount",
      "gender": "Gender",
      "dob": "Date Of Birth",
      "block": "BlockStatus",
      "normal": "Normal",
    },
    "ar_UE": {
      "home": "الرئيسية",
      "user": "إدارة المستخدم",
      'wallet': "محفظة",
      "language": "لغة",
      "no live": "لا أحد يعيش الآن",
      "totaluser": "إجمالي مستخدمي التطبيق",
      "follow": "يتبع",
      "follower": "تابع",
      "manage": "يدير",
      "blockuser": "المستخدمون المحظورون",
      "unblock": "إلغاء الحظر",
      "pandauser": "مستخدم باندا لايف المحبوب",
      "country": "دولة",
      "weekcoins": "العملات المكتسبة خلال الأسبوع",
      "weekearn": "أرباح الأسبوع",
      "totalwid": "إجمالي مبلغ السحب",
      "gender": "جنس",
      "dob": "تاريخ الميلاد",
      "block": "حالة الحظر",
      "normal": "طبيعي",
    },
  };
}
